package constants

import "time"

const (
	OpCreate                             = "create"
	OpGet                                = "get"
	OpList                               = "list"
	OpUpdate                             = "update"
	OpPatch                              = "patch"
	OpDelete                             = "delete"
	OpSync                               = "sync"
	ResourceUser                         = "users"
	ResourceGroup                        = "groups"
	ResourceCategory                     = "categories"
	ResourceRole                         = "roles"
	ResourceApplication                  = "applications"
	ResourceGlobalConfig                 = "global-config"
	ResourceAuthChallenge                = "auth-challenges"
	ResourceUserSession                  = "user-sessions"
	ResourceUserPasskey                  = "user-passkeys"
	ResourceSnapshot                     = "snapshots"
	ResourceDefault                      = "default"
	CachedResponse                       = "Cached response"
	ResourcePathPrefix                   = "resources/"
	NameParam                            = "name"
	IDParam                              = "id"
	LatestParam                          = "latest"
	ScopeParam                           = "scope"
	NamespaceParam                       = "namespace"
	GenerationParam                      = "generation"
	UsernameParam                        = "username"
	EmailParam                           = "email"
	UserIDParam                          = "userId"
	GroupIDParam                         = "groupId"
	TokenParam                           = "token"
	SpecField                            = "spec"
	MetadataField                        = "metadata"
	ResourceVersionField                 = "resourceVersion"
	ConflictStatus                       = 409
	ConflictMessageFragment              = "the object has been modified"
	AllowedEnvVarPattern                 = `^[A-Z_][A-Z0-9_]*$`
	MaxEnvVarLength                      = 8192
	CacheKeyPrefix                       = "cache"
	CacheGenerationSegment               = "generation"
	CacheTTL                             = 5 * time.Minute
	CacheRefreshInterval                 = 30 * time.Second
	DefaultPort                          = 8080
	EmptyString                          = ""
	IndexLastElementOffset               = 1
	IndexSecondLastElementOffset         = 2
	DefaultChannelBufferSize             = 1
	DefaultLastPasskeyCount              = 1
	DefaultInitValue                     = 0
	DefaultIncrementValue                = 1
	DefaultMajorPart                     = 2
	MinCategoriesInCRD                   = 1
	ServerReadTimeout                    = 30 * time.Second
	ServerWriteTimeout                   = 30 * time.Second
	HandlerDefaultTimeout                = 30 * time.Second
	ServerShutdownTimeout                = 30 * time.Second
	ServerIdleTimeout                    = 120 * time.Second
	SuccessStatus                        = 200
	PrefixCache                          = "Cache: "
	PrefixGenerics                       = "Generics: "
	PrefixLink                           = "Link: "
	PrefixOptimizer                      = "Optimizer: "
	PrefixMain                           = "Main: "
	PrefixStartup                        = "Startup: "
	PrefixShared                         = "Shared: "
	LogMessageWithError                  = "%s: %v"
	MaxHeaderBytes                       = 1 << 20 // 1MB
	DefaultRoutesCount                   = 35
	SnapshotInfosResponseFieldsCount     = 9
	SnapshotBytesPerKilobyte             = 1024
	SnapshotKilobytesPerMegabyte         = 1024
	SnapshotPercentScale                 = 100
	GlobalConfigResourceName             = "global-config"
	ManifestOrderServiceAccount          = 1
	ManifestOrderConfigMap               = 2
	ManifestOrderSecret                  = 3
	ManifestOrderPersistentVolumeClaim   = 4
	ManifestOrderService                 = 5
	ManifestOrderNetworkPolicy           = 6
	ManifestOrderDeployment              = 7
	ManifestOrderStatefulSet             = 8
	ManifestOrderDaemonSet               = 9
	ManifestOrderJob                     = 10
	ManifestOrderCronJob                 = 11
	ManifestOrderIngress                 = 12
	ManifestOrderHorizontalPodAutoscaler = 13
	ManifestOrderVerticalPodAutoscaler   = 14
	DefaultManifestUnknownOrder          = 99
	UserSpecMapCapacity                  = 8
	UserStatusMapCapacity                = 2
	UserStatusPhaseKey                   = "phase"
	MaxUserIDGenerationAttempts          = 10
	UUIDByteLength                       = 16
	UUIDLastByteIndex                    = 15
	ChallengeSpecMapCapacity             = 4
	SessionSpecMapCapacity               = 5
	PasskeySpecMapCapacity               = 6
	ChallengeSuffix                      = "-challenge"
	SessionSuffix                        = "-session"
	PasskeySuffix                        = "-passkey"
	ResourceTypeChallenge                = "challenge"
	SessionNamePrefix                    = "session-"
	SessionDigestLength                  = 64
	AIKeySecretNamespaceEnv              = "AI_KEY_SECRET_NAMESPACE"
	AIKeySecretNameEnv                   = "AI_KEY_SECRET_NAME"
	AIKeySecretField                     = "apiKey"
	ResourceTypePasskey                  = "passkey"
	FieldToken                           = "token"
	FieldCredentialID                    = "credentialId"
	FieldUsername                        = "username"
	FieldFullname                        = "fullname"
	FieldEmail                           = "email"
	FieldIdentities                      = "identities"
	FieldAvatar                          = "avatar"
	FieldStatus                          = "status"
	FieldID                              = "id"
	FieldVersion                         = "version"
	FieldGeneration                      = "generation"
	FieldName                            = "name"
	FieldItems                           = "items"
	FieldScope                           = "scope"
	FieldNamespace                       = "namespace"
	FieldType                            = "type"
	FieldCreationDate                    = "creationDate"
	FieldCategories                      = "categories"
	FieldManifest                        = "manifest"
	FieldTotalPVCSpace                   = "totalPVCSpace"
	FieldConsumedSpace                   = "consumedSpace"
	FieldAvailableSpace                  = "availableSpace"
	FieldTotalSnapshots                  = "totalSnapshots"
	FieldSnapshotsPath                   = "snapshotsPath"
	FieldSnapshotScopes                  = "snapshotScopes"
	FieldPVCName                         = "pvcName"
	FieldPVCNamespace                    = "pvcNamespace"
	FieldBytes                           = "bytes"
	FieldKilobytes                       = "kb"
	FieldMegabytes                       = "mb"
	FieldPercent                         = "percent"
	FieldResources                       = "resources"
	FieldAPIVersion                      = "apiVersion"
	FieldKind                            = "kind"
	FieldItemsManifest                   = "items"
	CategoriesCRDName                    = "categories"
	FieldUserIDs                         = "userIDs"
	FieldGroupIDs                        = "groupIDs"
	FieldAssignedUsersIDs                = "assignedUsersIDs"
	FieldAssignedRolesIDs                = "assignedRolesIDs"
	FieldAssignedGroupsIDs               = "assignedGroupsIDs"
	HeaderUserID                         = "X-User-ID"
	HeaderCredentialID                   = "X-Credential-ID"
	SnapshotsPathEnv                     = "SNAPSHOTS_PATH"
	SnapshotsMaxVersionsEnv              = "SNAPSHOTS_MAX_VERSIONS"
	SnapshotsPVCNameEnv                  = "SNAPSHOTS_PVC_NAME"
	SnapshotsPVCNamespaceEnv             = "SNAPSHOTS_PVC_NAMESPACE"
	SnapshotsAppsSubdir                  = "apps"
	DefaultSnapshotsPath                 = "/snapshots"
	DefaultSnapshotsMaxVersions          = 5
	MinSnapshotsMaxVersions              = 1
	VerIndex                             = 2
	DefaultSnapshotsPVCName              = "telark-exporter-snapshots-pvc"
	DefaultSnapshotsPVCNamespace         = "telark"
	SnapshotFileExtension                = ".json"
	SnapshotRollbackFilenameSuffix       = "-rollback.json"
	HeaderContentDisposition             = "Content-Disposition"
	HeaderContentType                    = "Content-Type"
	ContentTypeJSON                      = "application/json"
	ContentDispositionAttachmentTemplate = "attachment; filename=\"%s\""
	SnapshotLatestGenerationValue        = "latest"
	SnapshotDirPerm                      = 0o755
	// The star is where the unique part goes; the suffix keeps orphaned temp
	// files greppable.
	SnapshotTempSuffix = ".*.tmp"
	SnapshotGenerationMinValue           = 1
	KubernetesListAPIVersion             = "v1"
	KubernetesListKind                   = "List"
	KindServiceAccount                   = "ServiceAccount"
	KindConfigMap                        = "ConfigMap"
	KindSecret                           = "Secret"
	KindPersistentVolumeClaim            = "PersistentVolumeClaim"
	KindService                          = "Service"
	KindNetworkPolicy                    = "NetworkPolicy"
	KindDeployment                       = "Deployment"
	KindStatefulSet                      = "StatefulSet"
	KindDaemonSet                        = "DaemonSet"
	KindJob                              = "Job"
	KindCronJob                          = "CronJob"
	KindIngress                          = "Ingress"
	KindHorizontalPodAutoscaler          = "HorizontalPodAutoscaler"
	KindVerticalPodAutoscaler            = "VerticalPodAutoscaler"
	PasskeyDeviceTypePlatform            = "platform"
	PasskeyDeviceTypeCrossPlatform       = "cross-platform"
	UnknownValue                         = "unknown"
)
