{{- $service := "exporter" -}}
{{- $values := .Values -}}
{{- $serviceConfig := index $values.services $service -}}
{{- if and $serviceConfig.enabled $values.app.persistence.enabled }}
{{- $sc := $values.app.persistence.storageClass | default "" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $values.app.name }}-exporter-snapshots-pvc
  namespace: {{ $values.app.namespace }}
  labels:
    app.kubernetes.io/name: {{ $values.app.name }}-{{ $serviceConfig.name }}
    app.kubernetes.io/part-of: {{ $values.app.name }}
spec:
  accessModes:
    - {{ $values.app.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ $values.app.persistence.size | default "1Gi" }}
  {{- if $sc }}
  {{- if eq "-" $sc }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ $sc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
