package constants

const (
	JSONKeyError                  = "error"
	JSONKeySuccess                = "success"
	JSONKeyMessage                = "message"
	JSONKeyData                   = "data"
	JSONKeySelfRegEnabled         = "selfRegistrationEnabled"
	JSONKeyOIDCEnabled            = "oidcEnabled"
	JSONKeyGoogleClientID         = "googleClientID"
	ConfigMessage                 = "auth bootstrap config"
	HealthMessageHealthy          = "Service is healthy"
	HealthMessageNotReady         = "Service is not ready"
	PasskeyFieldDeviceName        = "deviceName"
	PasskeyFieldLastUsedTimestamp = "lastUsedTimestamp"
	RequestFieldUsername          = "username"
	DefaultForceLastDelete        = false
	DefaultCleanupOrphaned        = false
	DefaultWebAuthnEnforce        = true
	WebAuthnKeyID                 = "id"
	WebAuthnKeyResponse           = "response"
	WebAuthnKeyAttestationObject  = "attestationObject"
	WebAuthnKeyClientDataJSON     = "clientDataJSON"
	WebAuthnKeyAuthenticatorData  = "authenticatorData"
	WebAuthnKeyChallenge          = "challenge"
	WebAuthnKeyOrigin             = "origin"
	WebAuthnKeyFormat             = "fmt"
	WebAuthnKeyAuthData           = "authData"
	Base64URLMinus                = "-"
	Base64URLPlus                 = "+"
	Base64URLUnderscore           = "_"
	Base64URLSlash                = "/"
	Base64URLPadding              = "="
	BackupFlagErrorCapitalized    = "Backup Eligible flag inconsistency"
	BackupFlagErrorLowercase      = "backup eligible flag inconsistency"
	BackupFlagErrorGeneric        = "backup flag"
	TimeFormatRFC3339             = "2006-01-02T15:04:05Z07:00"
	GoogleIssuer                  = "https://accounts.google.com"
	OIDCJWKKeyType                = "RSA"
	OIDCJWKUse                    = "sig"
	OIDCJWKSFetchURL              = "https://www.googleapis.com/oauth2/v3/certs"
	IdentityProviderGoogle        = "google"
	IdentityProviderPasskey       = "passkey"
	UserFieldIdentities           = "identities"
	UserFieldStatus               = "status"
	UserStatusFieldPhase          = "phase"
	UserStatusFieldLastLoginAt    = "lastLoginAt"
	IdentityHashLength            = 8
	IdentityHashUnknown           = "unknown"
	TokenStatusValid              = "valid"
	TokenStatusExpired            = "expired"
	TokenStatusInvalid            = "invalid"
	TokenStatusRevokeFailed       = "revoke-failed"
)
