{{- $service := "discovery" -}}
{{- $values := .Values -}}
{{- $serviceConfig := index $values.services $service -}}
{{- if $serviceConfig.enabled }}
{{- include "serviceService" (dict "service" $service "values" $values "root" $) }}
{{- end }} 