apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.app.name }}-nats-secret
  namespace: {{ $.Values.app.namespace }}
  labels:
    {{- include "telark.labels" $ | nindent 4 }}
    app.kubernetes.io/component: nats
type: Opaque
data:
  username: bmF0cw==
  password: bmF0czEyMw==
