{{- if .Values.app.shared.redis }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-redis-cm
  namespace: {{ .Values.app.namespace }}
  labels:
    {{- include "telark.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
data:
{{- range $key, $value := .Values.app.shared.redis }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
