{{- if $.Values.services.exporter.enabled }}
{{- include "role" (dict "service" "exporter" "values" .Values "root" $ "rules" (list
  (dict "apiGroups" (list (include "telark.apiGroup" $)) "resources" (list "*" "*/*") "verbs" (list "*"))
  (dict "apiGroups" (list "") "resources" (list "persistentvolumeclaims") "verbs" (list "get" "list" "watch"))
  (dict "apiGroups" (list "") "resources" (list "secrets") "resourceNames" (list (include "telark.oidcTrustSecretName" $)) "verbs" (list "get" "update" "patch"))
)) }}
{{- end }}
