{{- $service := "notifier" -}}
{{- $serviceConfig := index .Values.services $service -}}
{{- if and $serviceConfig.pdb $serviceConfig.pdb.enabled }}
{{- include "servicePDB" (dict "service" $service "values" .Values "root" $) }}
{{- end }}
