{{- $service := "notifier" -}}
{{- $values := include "telark.modeValues" $ | fromYaml -}}
{{- $serviceConfig := index $values.services $service -}}
{{- if and $serviceConfig.pdb $serviceConfig.pdb.enabled }}
{{- include "servicePDB" (dict "service" $service "values" $values "root" $) }}
{{- end }}
