apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.app.name }}-reg-cred
  namespace: {{ $.Values.app.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJpbmRleC5kb2NrZXIuaW8iOnsidXNlcm5hbWUiOiJib3RyaWFjayIsInBhc3N3b3JkIjoiZG9ja2VydXNlcjEyMyIsImVtYWlsIjoiaG91c3NlbS5rcmFvdWFAZ21haWwuY29tIiwiYXV0aCI6IlltOTBjbWxoWTJzNlpHOWphMlZ5ZFhObGNqRXlNdz09In19fQ==
