kyverno:
  admissionController:
    replicas: 1
    podDisruptionBudget:
      enabled: false
    container:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          memory: 256Mi
      extraArgs:
        clientRateLimitQPS: 10
        clientRateLimitBurst: 20
    initContainer:
      resources:
        requests:
          cpu: 10m
          memory: 32Mi
        limits:
          memory: 64Mi
  backgroundController:
    replicas: 1
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
    extraArgs:
      clientRateLimitQPS: 10
      clientRateLimitBurst: 20
  cleanupController:
    replicas: 1
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
    extraArgs:
      clientRateLimitQPS: 10
      clientRateLimitBurst: 20
  reportsController:
    replicas: 1
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        memory: 128Mi
    extraArgs:
      clientRateLimitQPS: 10
      clientRateLimitBurst: 20
