kyverno:
  admissionController:
    replicas: 3
    podDisruptionBudget:
      enabled: true
      minAvailable: 2
    container:
      resources:
        requests:
          cpu: 500m
          memory: 512Mi
        limits:
          memory: 1Gi
      extraArgs:
        clientRateLimitQPS: 200
        clientRateLimitBurst: 400
    initContainer:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
  backgroundController:
    replicas: 2
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 512Mi
    extraArgs:
      clientRateLimitQPS: 200
      clientRateLimitBurst: 400
  cleanupController:
    replicas: 2
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 512Mi
    extraArgs:
      clientRateLimitQPS: 200
      clientRateLimitBurst: 400
  reportsController:
    replicas: 2
    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        memory: 512Mi
    extraArgs:
      clientRateLimitQPS: 200
      clientRateLimitBurst: 400
