{{- $service := "exporter" -}}
{{- $values := .Values -}}
{{- $serviceConfig := index $values.services $service -}}
{{- include "validateExporterStorage" (dict "values" $values "root" $) -}}
{{- if $serviceConfig.enabled }}
{{- include "serviceDeployment" (dict "service" $service "values" $values "root" $) }}
{{- end }}
