package protection

import (
	"github.com/telark/telark/internal/data/errors"
	"github.com/telark/telark/internal/data/plans"
)

const (
	SystemActor              = "system"
	KeyPrefixLockPlanName    = "lock:plan-name:"
	fmtWrappedErr            = "%w: %v"
	ReasonCanceledByUser     = "Canceled by user."
	ReasonExpired            = "Plan window ended."
	ReasonParked             = "Plan parked by an edit."
	QueryParamLimit          = "limit"
	QueryParamResult         = "result"
	FieldPhase               = "phase"
	FieldReason              = "reason"
	FieldRenderedPolicies    = "renderedPolicies"
	FieldTerminatedAt        = "terminatedAt"
	FieldTerminatedBy        = "terminatedBy"
	FieldLastUpdatedAt       = "lastUpdatedAt"
	FieldLastUpdatedBy       = "lastUpdatedBy"
	FieldHealth              = "health"
	FieldStartedAt           = "startedAt"
	FieldStartedBy           = "startedBy"
	FieldApprovalMode        = "approvalMode"
	FieldApproval            = "approval"
	FieldScope               = "scope"
	FieldScopeExclusions     = "exclusions"
	FieldExclusionKinds      = "kinds"
	FieldExclusionResources  = "resources"
	FieldExclusionKind       = "kind"
	FieldExclusionName       = "name"
	FieldExclusionNamespace  = "namespace"
	FieldApprovalState       = "state"
	FieldApprovalRequestedBy = "requestedBy"
	FieldApprovalRequestedAt = "requestedAt"
	FieldApprovalDecidedBy   = "decidedBy"
	FieldApprovalDecidedAt   = "decidedAt"
	FieldApprovalComment     = "comment"
	FieldApprovalHistory     = "history"
	DecisionApproved         = plans.ApprovalStateApproved
	DecisionRejected         = plans.ApprovalStateRejected
	ApprovalCommentMax       = 500
	LogPlanActivated         = "protection-plan activated plan=%s"
	LogPlanTerminated        = "protection-plan terminated plan=%s"
	LogPlanApproved          = "protection-plan approved plan=%s by=%s phase=%s"
	LogPlanRejected          = "protection-plan rejected plan=%s by=%s"
	LogPlanParked            = "protection-plan awaiting approval plan=%s requestedBy=%s"
	LogActivateSkippedStale  = "protection-plan activate skipped plan=%s phase=%s (no longer activatable)"
	LogStaleDeleteFailed     = "protection-plan update stale delete failed plan=%s err=%v"
	LogCleanupFailed         = "protection-plan %s cleanup failed plan=%s err=%v"
)

const (
	ErrUserMissing            errors.Error = "X-User-ID header is required"
	ErrMissingApplications    errors.Error = "applications not found: %v"
	ErrIgnoredApplications    errors.Error = "applications live only in namespaces the policy engine ignores: %v"
	ErrCancelInvalidPhase     errors.Error = "plan in phase %q cannot be canceled"
	ErrReactivateInvalidPhase errors.Error = "plan in phase %q cannot be reactivated"
	ErrReactivateExpired      errors.Error = "plan time range has fully elapsed;" +
		" edit the plan with new dates before reactivating"
	ErrReactivateMissingTemplates  errors.Error = "policy templates no longer exist: %v"
	ErrRequestBody                 errors.Error = "invalid request body: %v"
	ErrIDGeneration                errors.Error = "failed to generate plan id: %v"
	ErrInternal                    errors.Error = "internal error: %v"
	ErrServiceNotReady             errors.Error = "protection plan service is not ready"
	ErrReportBusy                  errors.Error = "a report is already being generated; retry shortly"
	ErrApprovalNotPending          errors.Error = "plan is not awaiting approval"
	ErrApprovalStale               errors.Error = "plan changed since the approval request was read; reload and decide again"
	ErrApprovalSelfDecision        errors.Error = "the requester cannot decide on their own approval request"
	ErrApprovalCommentRequired     errors.Error = "a comment is required to reject a plan"
	ErrApprovalCommentTooLong      errors.Error = "comment must be at most 500 characters"
	ErrApprovalRequestedAtRequired errors.Error = "requestedAt is required"
	ErrApprovalInvalidDecision     errors.Error = "decision must be one of: approved, rejected"
	ErrApprovalModeImmutable       errors.Error = "approvalMode cannot be changed; duplicate the plan instead"
	ErrApprovedPlanMaterialEdit    errors.Error = "an approved plan cannot be materially edited;" +
		" duplicate the plan, or cancel and reactivate it to re-request approval"
	ErrPlanDecisionInFlight        errors.Error = "a decision on this plan is already in progress; retry shortly"
	ErrPlanNameInFlight            errors.Error = "a plan with this name is being created or renamed; retry shortly"
	ErrPlanCoordinationUnavailable errors.Error = "plan coordination unavailable"
)
