name: 'Docker Login'
description: 'Log in to the container registry (ghcr.io).'
inputs:
  username:
    description: 'Container registry username'
    required: true
  password:
    description: 'Container registry password'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Docker Login
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: 'ghcr.io'
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
