{{- $values := include "telark.modeValues" $ | fromYaml -}}
{{- include "validateExporterStorage" (dict "values" $values "root" $) -}}
{{- include "validateSecuritySettings" $ -}}
{{- range $name, $svc := $values.services }}
{{- if $svc.enabled }}
---
{{ include "serviceDeployment" (dict "service" $name "values" $values "root" $) }}
{{- end }}
{{- end }}
