{{- $values := include "telark.modeValues" $ | fromYaml -}}
{{- range $name, $svc := $values.services }}
{{- if dig "pdb" "enabled" false $svc }}
---
{{ include "servicePDB" (dict "service" $name "values" $values "root" $) }}
{{- end }}
{{- end }}
