name: Build & Install Helm Release
run-name: Build & Install Helm Release with Bump "${{ inputs.build_type }}"
on:
  workflow_dispatch:
    inputs:
      build_type:
        required: false
        type: choice
        description: Build Type
        options:
          - patch
          - minor
          - major
      kyverno_config_mode:
        required: false
        type: choice
        description: Kyverno Config Mode
        options:
          - minimal
          - performance
        default: minimal

      sonar_scan:
        required: false
        type: choice
        description: SonarQube Scan
        options:
          - allow
          - skip
        default: skip

env:
  NAMESPACE: "telark"

jobs:
  trigger-helm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Helm Release Pipeline
        uses: peter-evans/repository-dispatch@v4
        with:
          repository: telark/release-manager
          token: ${{ secrets.ACCESS_TOKEN }}
          event-type: execute-telark-helm-release
          client-payload: '{"build_type": "${{ inputs.build_type }}", "ns": "${{ env.NAMESPACE }}", "sonar_scan": "${{ inputs.sonar_scan }}", "kyverno_config_mode": "${{ inputs.kyverno_config_mode }}"}'