"""Environment-based configuration: the only module that reads the environment."""

import os
import re

from dotenv import load_dotenv

from constants import (
    ANALYZER_MODES,
    APPLICATION_GET_PATH,
    APPLICATIONS_LIST_PATH,
    PLAN_ENVIRONMENTS_PATH,
    PLANS_LIST_PATH,
    AUTHZ_PERMISSIONS_PATH,
    DEFAULT_ANALYZER_AUTO_COOLDOWN_SEC,
    DEFAULT_ANALYZER_CHARS_PER_TOKEN,
    DEFAULT_ANALYZER_CONFIG_POLL_SEC,
    DEFAULT_ANALYZER_CONTEXT_TOKENS,
    DEFAULT_ANALYZER_EMIT_TIMEOUT_SEC,
    DEFAULT_ANALYZER_LOOP_TIMEOUT_SEC,
    DEFAULT_ANALYZER_MANUAL_COOLDOWN_SEC,
    DEFAULT_ANALYZER_MAX_STEPS,
    DEFAULT_ANALYZER_MAX_TOOL_CALLS,
    DEFAULT_ANALYZER_MODE,
    DEFAULT_ANALYZER_NARRATE_TIMEOUT_SEC,
    DEFAULT_ANALYZER_NUM_THREAD,
    DEFAULT_ANALYZER_REVIEW_INTERVAL_SEC,
    DEFAULT_ANALYZER_REVIEW_TICK_SEC,
    DEFAULT_ANALYZER_REVIEW_APPS_PER_MIN,
    DEFAULT_ANALYZER_REVIEW_WORKLOADS_MAX,
    DEFAULT_ANALYZER_USAGE_MIN_SAMPLES,
    DEFAULT_ANALYZER_USAGE_MIN_SPAN_SEC,
    DEFAULT_ANALYZER_CHANGE_VELOCITY_PER_DAY,
    DEFAULT_ANALYZER_CHANGE_RISK_MIN_SPAN_SEC,
    DEFAULT_ANALYZER_PRODUCTION_PATTERN,
    ENV_ANALYZER_REVIEW_INTERVAL_SEC,
    ENV_ANALYZER_REVIEW_TICK_SEC,
    ENV_ANALYZER_REVIEW_APPS_PER_MIN,
    ENV_ANALYZER_REVIEW_WORKLOADS_MAX,
    ENV_ANALYZER_USAGE_MIN_SAMPLES,
    ENV_ANALYZER_USAGE_MIN_SPAN_SEC,
    ENV_ANALYZER_CHANGE_VELOCITY_PER_DAY,
    ENV_ANALYZER_CHANGE_RISK_MIN_SPAN_SEC,
    ENV_ANALYZER_PRODUCTION_PATTERN,
    DEFAULT_ANALYZER_QUEUE_MAX,
    DEFAULT_ANALYZER_TOOL_RESULT_MAX_BYTES,
    DEFAULT_ANALYZER_WALL_SEC,
    DEFAULT_API_PORT,
    DEFAULT_AUTH_SERVICE_URL,
    DEFAULT_EXPORTER_SERVICE_URL,
    DEFAULT_LOG_LEVEL,
    DEFAULT_OLLAMA_AUTO_PULL,
    DEFAULT_OLLAMA_HOST,
    DEFAULT_REDIS_HOST,
    DEFAULT_REDIS_POOL_SIZE,
    DEFAULT_REDIS_PORT,
    DEFAULT_SERVICE_TOKEN,
    ENV_ANALYZER_AUTO_COOLDOWN_SEC,
    ENV_ANALYZER_CHARS_PER_TOKEN,
    ENV_ANALYZER_CONFIG_POLL_SEC,
    ENV_ANALYZER_CONTEXT_TOKENS,
    ENV_ANALYZER_EMIT_TIMEOUT_SEC,
    ENV_ANALYZER_LOOP_TIMEOUT_SEC,
    ENV_ANALYZER_MANUAL_COOLDOWN_SEC,
    ENV_ANALYZER_MAX_STEPS,
    ENV_ANALYZER_MAX_TOOL_CALLS,
    ENV_ANALYZER_MODE,
    ENV_ANALYZER_NARRATE_TIMEOUT_SEC,
    ENV_ANALYZER_NUM_THREAD,
    ENV_ANALYZER_QUEUE_MAX,
    ENV_ANALYZER_TOOL_RESULT_MAX_BYTES,
    ENV_ANALYZER_WALL_SEC,
    ENV_API_PORT,
    ENV_AUTH_SERVICE_URL,
    ENV_EXPORTER_SERVICE_URL,
    ENV_LOG_LEVEL,
    ENV_OLLAMA_AUTO_PULL,
    ENV_OLLAMA_HOST,
    ENV_REDIS_HOST,
    ENV_REDIS_POOL_SIZE,
    ENV_REDIS_PORT,
    ENV_REDIS_URL,
    ENV_SERVICE_TOKEN,
    ENV_TRUE_VALUES,
    GLOBALCONFIG_PATH,
    REDIS_URL_TEMPLATE,
)

load_dotenv()


def _int(name: str, default: int) -> int:
    return int(os.environ.get(name, str(default)))


def _float(name: str, default: float) -> float:
    return float(os.environ.get(name, str(default)))


def _bool(name: str, default: bool) -> bool:
    return os.environ.get(name, str(default)).strip().lower() in ENV_TRUE_VALUES


# REDIS_URL overrides REDIS_HOST + REDIS_PORT when set.
REDIS_HOST: str = os.environ.get(ENV_REDIS_HOST, DEFAULT_REDIS_HOST)
REDIS_PORT: str = os.environ.get(ENV_REDIS_PORT, DEFAULT_REDIS_PORT)
REDIS_URL: str = os.environ.get(ENV_REDIS_URL) or REDIS_URL_TEMPLATE.format(REDIS_HOST, REDIS_PORT)
REDIS_POOL_SIZE: int = _int(ENV_REDIS_POOL_SIZE, DEFAULT_REDIS_POOL_SIZE)

OLLAMA_HOST: str = os.environ.get(ENV_OLLAMA_HOST, DEFAULT_OLLAMA_HOST)
OLLAMA_AUTO_PULL: bool = _bool(ENV_OLLAMA_AUTO_PULL, DEFAULT_OLLAMA_AUTO_PULL)

LOG_LEVEL: str = os.environ.get(ENV_LOG_LEVEL, DEFAULT_LOG_LEVEL)
API_PORT: int = _int(ENV_API_PORT, DEFAULT_API_PORT)

AUTH_SERVICE_URL: str = os.environ.get(ENV_AUTH_SERVICE_URL, DEFAULT_AUTH_SERVICE_URL)
AUTHZ_PERMISSIONS_URL: str = AUTH_SERVICE_URL.rstrip("/") + AUTHZ_PERMISSIONS_PATH

EXPORTER_SERVICE_URL: str = os.environ.get(ENV_EXPORTER_SERVICE_URL, DEFAULT_EXPORTER_SERVICE_URL)
GLOBALCONFIG_URL: str = EXPORTER_SERVICE_URL.rstrip("/") + GLOBALCONFIG_PATH
APPLICATION_URL_TEMPLATE: str = EXPORTER_SERVICE_URL.rstrip("/") + APPLICATION_GET_PATH
APPLICATIONS_URL: str = EXPORTER_SERVICE_URL.rstrip("/") + APPLICATIONS_LIST_PATH
PLANS_URL: str = EXPORTER_SERVICE_URL.rstrip("/") + PLANS_LIST_PATH
PLAN_ENVIRONMENTS_URL: str = EXPORTER_SERVICE_URL.rstrip("/") + PLAN_ENVIRONMENTS_PATH
SERVICE_TOKEN: str = os.environ.get(ENV_SERVICE_TOKEN, DEFAULT_SERVICE_TOKEN)

ANALYZER_MAX_STEPS: int = _int(ENV_ANALYZER_MAX_STEPS, DEFAULT_ANALYZER_MAX_STEPS)
ANALYZER_MAX_TOOL_CALLS: int = _int(ENV_ANALYZER_MAX_TOOL_CALLS, DEFAULT_ANALYZER_MAX_TOOL_CALLS)
ANALYZER_TOOL_RESULT_MAX_BYTES: int = _int(
    ENV_ANALYZER_TOOL_RESULT_MAX_BYTES, DEFAULT_ANALYZER_TOOL_RESULT_MAX_BYTES
)
ANALYZER_WALL_SEC: int = _int(ENV_ANALYZER_WALL_SEC, DEFAULT_ANALYZER_WALL_SEC)
ANALYZER_LOOP_TIMEOUT_SEC: int = _int(ENV_ANALYZER_LOOP_TIMEOUT_SEC, DEFAULT_ANALYZER_LOOP_TIMEOUT_SEC)
ANALYZER_EMIT_TIMEOUT_SEC: int = _int(ENV_ANALYZER_EMIT_TIMEOUT_SEC, DEFAULT_ANALYZER_EMIT_TIMEOUT_SEC)
ANALYZER_CHARS_PER_TOKEN: float = _float(ENV_ANALYZER_CHARS_PER_TOKEN, DEFAULT_ANALYZER_CHARS_PER_TOKEN)
ANALYZER_CONTEXT_TOKENS: int = _int(ENV_ANALYZER_CONTEXT_TOKENS, DEFAULT_ANALYZER_CONTEXT_TOKENS)
ANALYZER_QUEUE_MAX: int = _int(ENV_ANALYZER_QUEUE_MAX, DEFAULT_ANALYZER_QUEUE_MAX)
ANALYZER_AUTO_COOLDOWN_SEC: int = _int(ENV_ANALYZER_AUTO_COOLDOWN_SEC, DEFAULT_ANALYZER_AUTO_COOLDOWN_SEC)
ANALYZER_MANUAL_COOLDOWN_SEC: int = _int(
    ENV_ANALYZER_MANUAL_COOLDOWN_SEC, DEFAULT_ANALYZER_MANUAL_COOLDOWN_SEC
)
ANALYZER_CONFIG_POLL_SEC: int = _int(ENV_ANALYZER_CONFIG_POLL_SEC, DEFAULT_ANALYZER_CONFIG_POLL_SEC)
ANALYZER_NUM_THREAD: int = _int(ENV_ANALYZER_NUM_THREAD, DEFAULT_ANALYZER_NUM_THREAD)
ANALYZER_NARRATE_TIMEOUT_SEC: int = _int(ENV_ANALYZER_NARRATE_TIMEOUT_SEC, DEFAULT_ANALYZER_NARRATE_TIMEOUT_SEC)
ANALYZER_MODE: str = os.environ.get(ENV_ANALYZER_MODE, DEFAULT_ANALYZER_MODE)
# A typo must fail the pod loudly, never silently pick a mode.
if ANALYZER_MODE not in ANALYZER_MODES:
    raise ValueError(ENV_ANALYZER_MODE)

ANALYZER_REVIEW_INTERVAL_SEC: int = _int(ENV_ANALYZER_REVIEW_INTERVAL_SEC, DEFAULT_ANALYZER_REVIEW_INTERVAL_SEC)
ANALYZER_REVIEW_TICK_SEC: int = _int(ENV_ANALYZER_REVIEW_TICK_SEC, DEFAULT_ANALYZER_REVIEW_TICK_SEC)
ANALYZER_REVIEW_APPS_PER_MIN: int = _int(ENV_ANALYZER_REVIEW_APPS_PER_MIN, DEFAULT_ANALYZER_REVIEW_APPS_PER_MIN)
ANALYZER_REVIEW_WORKLOADS_MAX: int = _int(ENV_ANALYZER_REVIEW_WORKLOADS_MAX, DEFAULT_ANALYZER_REVIEW_WORKLOADS_MAX)
ANALYZER_USAGE_MIN_SAMPLES: int = _int(ENV_ANALYZER_USAGE_MIN_SAMPLES, DEFAULT_ANALYZER_USAGE_MIN_SAMPLES)
ANALYZER_USAGE_MIN_SPAN_SEC: int = _int(ENV_ANALYZER_USAGE_MIN_SPAN_SEC, DEFAULT_ANALYZER_USAGE_MIN_SPAN_SEC)
ANALYZER_CHANGE_VELOCITY_PER_DAY: float = _float(
    ENV_ANALYZER_CHANGE_VELOCITY_PER_DAY, DEFAULT_ANALYZER_CHANGE_VELOCITY_PER_DAY)
ANALYZER_CHANGE_RISK_MIN_SPAN_SEC: int = _int(
    ENV_ANALYZER_CHANGE_RISK_MIN_SPAN_SEC, DEFAULT_ANALYZER_CHANGE_RISK_MIN_SPAN_SEC)
# Compiled once: an invalid regex fails the pod at start, never a review.
ANALYZER_PRODUCTION_PATTERN: re.Pattern = re.compile(
    os.environ.get(ENV_ANALYZER_PRODUCTION_PATTERN, DEFAULT_ANALYZER_PRODUCTION_PATTERN), re.IGNORECASE)
